image: gradle:8.0.0-jdk17-alpine


definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: threem
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - gradle
            script:
              - gradle build
            services:
              - postgres
            after-script:
              - pipe: atlassian/checkstyle-report:0.3.0
        - step:
            name: Deploy to test
            deployment: test
            # trigger: manual  # Uncomment to make this a manual deployment.
            script:
              - echo "Deploying to test environment"
        - step:
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.5.1
