spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDB}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
