name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: ./gradlew build

  deploy:
      runs-on: ubuntu-latest
      env:
        ORG_PROJECT: Threem
        DEPLOY_ENV: dev
        SERVICE_NAME: threem-api
        RUNNER_NAME: scaledynamics-shared-runner
      steps:
          - uses: actions/checkout@v3

          - name: Connection to ScaleDynamics
            run: npx warp login --api-key=${{ secrets.THREEM_API_KEY }}
          
          - name: Create project
            run: npx warp project create "Threem"

          - name: Create env
            run: npx warp env create ${DEPLOY_ENV} --project ${ORG_PROJECT}

          - name: Configure env
            run: npx warp env base-url add ${SERVICE_NAME} "" --project ${ORG_PROJECT} --env ${DEPLOY_ENV}

          - name: Configure runner
            run: npx warp env runner set ${SERVICE_NAME} ${RUNNER_NAME} --project ${ORG_PROJECT} --env ${DEPLOY_ENV}

#             # Deploy a Dockerfile from a 'my-container' directory
#             warp --api-key "$APIKEY" deploy --project "$PROJECT" --env "$ENV" my-container

          - name: Deploy application
            run: npx warp deploy --project ${ORG_PROJECT} --env ${DEPLOY_ENV}
